DROP TABLE CURRENCY_MAPPING;

CREATE TABLE CURRENCY_MAPPING(
  CODE VARCHAR(10),
  CHINESE_NAME VARCHAR(20)
);

INSERT INTO CURRENCY_MAPPING(CODE, CHINESE_NAME) VALUES('USD', '美金');
INSERT INTO CURRENCY_MAPPING(CODE, CHINESE_NAME) VALUES('GBP', '英鎊');
INSERT INTO CURRENCY_MAPPING(CODE, CHINESE_NAME) VALUES('EUR', '歐元');